### ISSUE TITLE
Excuse me, I want to ask about using docker with your project

### ISSUE THREAD

**Issue by dinhan92** [thomasduft/openiddict-ui#10]
Everything run fine when I ran it without docker, but when I use docker, I ran into this error: System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'. when I use Postman to get the Api (https://localhost:5001/api/Resource/private) after Login.

Here is my Docker compose: 

version: '3'
services:
  api:
    build: Api/
    ports:
      - "5002:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  server:
    build: openiddict-ui/
    ports:
      - "4999:80"
      - "5000:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5000"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  
Here is my Dockerfile Sever:

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
RUN dotnet tool install -g dotnet-ef
ENV PATH $PATH:/root/.dotnet/tools
RUN dotnet ef --version
RUN apt-get update
RUN apt-get -y install sqlite3 libsqlite3-dev
WORKDIR /app

COPY *.sln ./
COPY samples/Server/*.csproj ./samples/Server/
COPY tests/*.csproj ./tests/
COPY src/suite/OpenIddict.UI.Suite.Api/*.csproj ./src/suite/OpenIddict.UI.Suite.Api/
COPY src/suite/OpenIddict.UI.Suite.Core/*.csproj ./src/suite/OpenIddict.UI.Suite.Core/
COPY src/openiddict/OpenIddict.UI.Api/*.csproj ./src/openiddict/OpenIddict.UI.Api/
COPY src/openiddict/OpenIddict.UI.Infrastructure/*.csproj ./src/openiddict/OpenIddict.UI.Infrastructure/
COPY src/identity/OpenIddict.UI.Identity.Api/*.csproj ./src/identity/OpenIddict.UI.Identity.Api/
COPY src/identity/OpenIddict.UI.Identity.Core/*.csproj ./src/identity/OpenIddict.UI.Identity.Core/
COPY src/identity/OpenIddict.UI.Identity.Infrastructure/*.csproj ./src/identity/OpenIddict.UI.Identity.Infrastructure/
RUN dotnet restore
COPY . ./

WORKDIR /app/samples/Server
RUN dotnet build -c Release -o out

WORKDIR /app/tests
RUN dotnet build -c Release -o out

WORKDIR /app/src/suite/OpenIddict.UI.Suite.Api
RUN dotnet build -c Release -o out

WORKDIR /app/src/suite/OpenIddict.UI.Suite.Core
RUN dotnet build -c Release -o out

WORKDIR /app/src/openiddict/OpenIddict.UI.Api
RUN dotnet build -c Release -o out

WORKDIR /app/src/openiddict/OpenIddict.UI.Infrastructure
RUN dotnet build -c Release -o out

WORKDIR /app/src/identity/OpenIddict.UI.Identity.Api
RUN dotnet build -c Release -o out

WORKDIR /app/src/identity/OpenIddict.UI.Identity.Core
RUN dotnet build -c Release -o out

WORKDIR /app/src/identity/OpenIddict.UI.Identity.Infrastructure
RUN dotnet build -c Release -o out

WORKDIR /app/samples/Server
RUN dotnet ef database update -c ApplicationDbContext
RUN dotnet ef database update -c OpenIddictUIContext
RUN dotnet ef database update -c OpenIddictUIIdentityContext
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Server.dll"]

Here is my Dockerfile Api:

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
RUN apt-get update
RUN apt-get -y install sqlite3 libsqlite3-dev
WORKDIR /app/api

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app/api
COPY --from=build-env /app/api/out .
ENTRYPOINT ["dotnet", "Api.dll"]

**Comment by dinhan92** [comment]
The actual error I get is: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
demomicroservice-api-1     |       An unhandled exception has occurred while executing the request.
demomicroservice-api-1     |       System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
demomicroservice-api-1     |        ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5000)
demomicroservice-api-1     |        ---> System.Net.Sockets.SocketException (99): Cannot assign requested address

However when I run the server in docker and run api not in docker, it still run fine, so I guess there should be something that prevent 2 images connecting each other. Do you have any idea?

**Comment by thomasduft** [comment]
Hi there

Look I won't really deep dive here for I do not have a docker image ready for the openiddict-ui sample server.

On the other hand it seems to me that you do not consider to seed the correct **Issuer** url for your use case when putting the sample server into a docker image. You have to put the correct Issuer url in place (i.e. [here](https://github.com/thomasduft/openiddict-ui/blob/7d7df60be9faab183e15df69b37e9096b2473db7/samples/Server/Startup.cs#L96) and [here](https://github.com/thomasduft/openiddict-ui/blob/7d7df60be9faab183e15df69b37e9096b2473db7/samples/Server/Services/MigrationService.cs#L61)). You need to be aware that the domain within the container is not the same that should be mapped to the outside when running a docker container. Otherwise it could end up in some errors you mentioned.

Maybe you find a hint [here](https://github.com/thomasduft/microsts/blob/4688777879877d85e12a0324c3f75eff6f8b8699/src/web/Services/MigrationService.cs#L50) where I have an old STS project built on the IdentityServer4 stack. 

Hope I could help in that sense.

Have a nice day, Thomas
