### ISSUE TITLE
Add possibility to use api without ADMIN role

### ISSUE THREAD

**Issue by Soruk** [thomasduft/openiddict-ui#12]
Hi,

I use your API using client credential flow, and my application do not have Administrator role and therefore I had to create a custom IAuthorizationHandler with verification of specific claims in order to allow the usage of API.
It would be great to find a prettier to do this. Do you have  any ideas?
```[CSharp]
public class SpecificApiAuthorizationHandler : IAuthorizationHandler
    {

        private readonly OpenIddictConfigurationOptions _openIdDictSettings;
        private readonly HashSet<string> _authorizedScopes;

        public SpecificApiAuthorizationHandler(
            IOptions<OpenIddictConfigurationOptions> openIdDictOptions)
        {
            _openIdDictSettings = (openIdDictOptions ??
                throw new ArgumentNullException(nameof(openIdDictOptions))).Value;

            _authorizedScopes = new HashSet<string>(_openIdDictSettings.AuthorizedApiScope, StringComparer.OrdinalIgnoreCase);
        }

        public Task HandleAsync(AuthorizationHandlerContext context)
        {

            //if (context.Resource is HttpContext httpContext)
            //{
            //    var endpoint = httpContext.GetEndpoint();                
            //    var actionDescriptor = endpoint.Metadata.GetMetadata<ControllerActionDescriptor>();
            //}

            var pendingRequirements = context.PendingRequirements.ToList();

            foreach (var requirement in pendingRequirements)
            {
                if (requirement is RolesAuthorizationRequirement rolesAuthorizationRequirement)
                {
                    if (rolesAuthorizationRequirement.AllowedRoles.Contains(Roles.ADMINISTRATOR_ROLE))
                    {
                        if (IsAdmin(context.User, context.Resource) || HasClaimAuthorizedScope(context.User, context.Resource))
                        {
                            context.Succeed(rolesAuthorizationRequirement);
                        }
                    }
                }
            }
            return Task.CompletedTask;
        }


        private bool IsAdmin(ClaimsPrincipal user, object? resource)
        {
            return user.IsInRole(Roles.ADMINISTRATOR_ROLE);
        }

        private bool HasClaimAuthorizedScope(ClaimsPrincipal user, object? resource)
        {
            return user.HasClaim(c => c.Type == Claims.Scope
                && c.Issuer.Equals(_openIdDictSettings.Authority, StringComparison.OrdinalIgnoreCase)
                && c.Value.Split(" ").Any(s => _authorizedScopes.Contains(s)));

        }
    }
```

**Comment by thomasduft** [comment]
Hi there

Can you elaborate a bit more on your use case? The [Aridka](https://github.com/openiddict/openiddict-samples/tree/dev/samples/Aridka) openiddict-sample basically addresses this issue.

Are you trying to get/push data to the **admin** endpoints openiddict-ui provides? Those are not intended to be used with / by clients. I built them mainly in order to expose minimalistic endpoints to create a small STS (Security Token Service) as the samples directory show-cases. That's why all of the endpoints are secured by the [Admin-policy](https://github.com/thomasduft/openiddict-ui/blob/7d7df60be9faab183e15df69b37e9096b2473db7/src/suite/OpenIddict.UI.Suite.Core/Common/Constants.cs#L5).

Hope that explains my intentions.

**Comment by thomasduft** [comment]
Ok now I got your idea...

What I can think of is to have some sort of opt-in possibility when setting up the policy [here](https://github.com/thomasduft/openiddict-ui/blob/7d7df60be9faab183e15df69b37e9096b2473db7/src/openiddict/OpenIddict.UI.Api/DependencyInjection.cs#L54)

```csharp
    private static IServiceCollection AddAuthorizationServices(
      this IServiceCollection services
    )
    {
      services.AddAuthorization(options =>
      {
        options.AddPolicy(
          Policies.ADMIN_POLICY,
          policy => policy
            .RequireAuthenticatedUser()
            .RequireRole(Roles.ADMINISTRATOR_ROLE)
        );
      });

      return services;
    }
```
The idea would be that anyone can/requires to implement their own policy. It would also require that there are dedicated Policy-names (one for the openiddict-ui and one for the openiddict-ui-identity). This would mean the `Authorize`-attributes on the corresponding endpoint-controllers need to be adjusted with the appropriate Policy-name.

An integrator could than add an own policy when bootstrapping the application whit own "rules" (roles, claims, etc.).

**Comment by Soruk** [comment]
Hi @thomasduft 

> Hi there
> 
> Can you elaborate a bit more on your use case? The [Aridka](https://github.com/openiddict/openiddict-samples/tree/dev/samples/Aridka) openiddict-sample basically addresses this issue.
> 
> Are you trying to get/push data to the **admin** endpoints openiddict-ui provides? Those are not intended to be used with / by clients. I built them mainly in order to expose minimalistic endpoints to create a small STS (Security Token Service) as the samples directory show-cases. That's why all of the endpoints are secured by the [Admin-policy](https://github.com/thomasduft/openiddict-ui/blob/7d7df60be9faab183e15df69b37e9096b2473db7/src/suite/OpenIddict.UI.Suite.Core/Common/Constants.cs#L5).
> 
> Hope that explains my intentions.
I want to use my internal api that calls your api using client flow credentials (therefore there is no user with admin role) for creating and deleting applications (clients, btw there is something wrong with update endpoint [I will open a new issue on that matter when I have some time])  And I didn't want to duplicate your code to that.
I have just looked at [Aridka](https://github.com/openiddict/openiddict-samples/tree/dev/samples/Aridka) example, the ```ResourceController``` shows the usage of ```IOpenIddictApplicationManager ``` ,  and with this I can manage applications on creating custom controller.
But if your api allows to do the same, I think it is better to allow the given usage.

**Comment by Soruk** [comment]
Hi @thomasduft , I think that this proposal would work for me.
Thanks.
