### ISSUE TITLE
IApplicationService.GetApplicationsAsync doesn't fill Permissions and RedirectUris

### ISSUE THREAD

**Issue by Khaos66** [thomasduft/openiddict-ui#18]
When using the `IApplicationService.GetApplicationsAsync` method, the result list contains `ApplicationInfo` instances with 0 `Permissions` and `RedirectUris`.

**Comment by thomasduft** [comment]
Hi @Khaos66 

Could you please elaborate more on your issue?

I slightly improved the Integration test [`ApplicationApiTest.GetAsyncApplicationReceived`](https://github.com/thomasduft/openiddict-ui/blob/5f9f42696c346ae0c40f8bad242fd86530eab4c2/tests/Integration/ApplicationApiTest.cs#L97) and could not reproduce the issue. 

I am not saying that there isn't a bug but so far not one that keeps me stop using my library ;-).

Greets Thomas

**Comment by Khaos66** [comment]
Hi @thomasduft 
I was trying to display the registered aps with their permissions and redirect uris. Sadly `GetApplicationsAsync` wasn't filling these things on the returned list. The returned application instances never showed any permissions or redirect uris. 
When I used the native OpenIDDict API however, the apps definetly had permissions and redirect uris.
If that's nothing you can verify, I'm fine with that, as I now just use the workaround ;)
