### ISSUE TITLE
Infinit loop. Data is not storing in session storage. it call the authorization again and again.

### ISSUE THREAD

**Issue by SooRaj-1994** [thomasduft/openiddict-ui#21]
I created an angular app based on this repo. Then I tried to public. It redirected to the openiddcit server and login was successful. But on redirection to my angular app from the authentication server. The it is looping in the angular app. It call the authorization again and again. No data is stored inside the local storage.

It is working fine in localhost.

**Comment by thomasduft** [comment]
Hi @SooRaj-1994

What you are describing is more of a wrong configuration to me than an issue for this repo. Please consider having a look at the angular frontend sample in this repo and how it is configured. It might help in finding your issue with your angular based frontend.

Cheers Thomas
