### ISSUE TITLE
sql server

### ISSUE THREAD

**Issue by itoop2019** [thomasduft/openiddict-ui#3]
Hey!
Tell me, please, how to switch the database to sql server?

**Comment by itoop2019** [comment]
I made a db sql-server, it works. Thought you had a ready-made solution.

**Comment by thomasduft** [comment]
Hi there
Sorry for answering late. I was camping a few days and not connected ;-).
Good you solved it on your way. I think if you replace the **UseSqlite** with **UseSqlServer** in my sample server's Startup.cs file and do the migrations correctly you should be good to go.
Hope that gave you another idea.

**Comment by itoop2019** [comment]
thank you, it worked and it works!
