### ISSUE TITLE
Excuse me, I want to ask about database update

### ISSUE THREAD

**Issue by dinhan92** [thomasduft/openiddict-ui#9]
When I run dotnet ef database update, I run into this error: More than one DbContext was found. Specify which one to use

I notice that you have more than 1 DbContext. So how to fix this?

**Comment by dinhan92** [comment]
Ok I solved this

**Comment by thomasduft** [comment]
Hi there

You need to consider the following DbContext's, dependent what you are using:
- **ApplicationDbContext**: cares about your application specific DB-Schema models. Might have an other name!
- **OpenIddictUIContext**: cares about the OpenIddict dependent DB-Schema models
- **OpenIddictUIIdentityContext**: cares about the ASP.NET Identity related DB-Schema models
